### PR TITLE
Took out grade 7 and literacy tests off the portal

### PR DESCRIPTION
**Pull request by ntipachola**
### Summary

…

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch
- [x] PR has 'needs review' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included

### Reviewer Checklist

- PR is fully functional
- PR has been tested for [accessibility regressions]
- External dependency files were updated if necessary (node_modules, libraries, etc)
- Documentation is updated

### CODE REVIEW

**Comment by techZM** [comment]
Please fill in the pull request template. It's not there for decoration!!

**Comment by ntipachola** [comment]
I filled up the template yesterday

*Ntipa Chola* | Tech Support

(+260 96 992 9538 | * nchola@edulution.org I www.edulution.org

**Comment by techZM** [comment]
The PR template has not been filled in. Ticking boxes does not mean it is filled in
blank_pr_template

**Comment by ntipachola** [comment]
Removed the button and link for literacy and revision test

**Pull request closed without merging**
